# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :playstore do

    latest_version_code = google_play_track_version_codes(
      track: "internal"
    ).max

    new_version_code = latest_version_code + 1
    UI.message("Incremented version code to #{new_version_code}")

  gradle(
    task: 'bundle',
    build_type: 'Release',
    properties: {
      "VERSION_CODE" => new_version_code,
      "VERSION_NAME" => new_version_code
    }
  )
  upload_to_play_store(
    track: "internal",
    track_promote_to: "beta",
    skip_upload_apk: true # use bundle instead
  )
end
